version: '3'

services:

  zookeeper-01:
    image: bitnami/zookeeper:latest
    restart: unless-stopped
    networks:
      nw_prognimak: null
    environment:
      ZOO_SERVER_ID: 1
      ZK_tickTime: 2000
      ZK_dataDir: '/data/zookeeper'
      ZOO_PORT_NUMBER: 2181
      ZK_initLimit: 5
      ZK_syncLimit: 2
      ZOO_SERVERS: '0.0.0.0:2888:3888,zookeeper-02:2888:3888,zookeeper-03:2888:3888'
      ALLOW_ANONYMOUS_LOGIN: 'yes'
    volumes:
      - vol-zk-1:/zookeeper

  zookeeper-02:
    image: bitnami/zookeeper:latest
    restart: unless-stopped
    networks:
      nw_prognimak: null
    environment:
      ZOO_SERVER_ID: 2
      ZK_tickTime: 2000
      ZK_dataDir: '/data/zookeeper'
      ZOO_PORT_NUMBER: 2181
      ZK_initLimit: 5
      ZK_syncLimit: 2
      ZOO_SERVERS: 'zookeeper-01:2888:3888,0.0.0.0:2888:3888,zookeeper-03:2888:3888'
      ALLOW_ANONYMOUS_LOGIN: 'yes'
    volumes:
      - vol-zk-2:/zookeeper

  zookeeper-03:
    image: bitnami/zookeeper:latest
    restart: unless-stopped
    networks:
      nw_prognimak: null
    environment:
      ZOO_SERVER_ID: 3
      ZK_tickTime: 2000
      ZK_dataDir: '/data/zookeeper'
      ZOO_PORT_NUMBER: 2181
      ZK_initLimit: 5
      ZK_syncLimit: 3
      ZOO_SERVERS: 'zookeeper-01:2888:3888,zookeeper-02:2888:3888,0.0.0.0:2888:3888'
      ALLOW_ANONYMOUS_LOGIN: 'yes'
    volumes:
      - vol-zk-3:/zookeeper

  kafka-01:
    image: bitnami/kafka:latest
    restart: unless-stopped
    networks:
      nw_prognimak: null
    ports:
      - 9093:9092
    environment:
      KAFKA_PORT: 9092
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_HOST_NAME: kafka-01
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-01:2181'
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 36000
      KAFKA_CFG_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_CFG_CREATE_TOPICS: 'test:1:1'
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 1
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_JMX_OPTS: '-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false  -Dcom.sun.management.jmxremote.ssl=false'
    volumes:
      - vol-kafka-1:/kafka
    depends_on:
      - zookeeper-01


  kafka-02:
    image: bitnami/kafka:latest
    restart: unless-stopped
    networks:
      nw_prognimak: null
    ports:
      - 9092:9092
    environment:
      KAFKA_PORT: 9092
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_HOST_NAME: kafka-02
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-02:2181'
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 36000
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 1
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_JMX_OPTS: '-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false  -Dcom.sun.management.jmxremote.ssl=false'
    volumes:
      - vol-kafka-2:/kafka
    depends_on:
      - zookeeper-02

  postgres:
    environment:
      PGDATA: /var/lib/postgresql-ftu/data/pgdata
      POSTGRES_INITDB_ARGS: --data-checksums
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
    hostname: postgres
    image: postgres:14
    networks:
      nw_prognimak: null
    ports:
      - 5455:5432
    volumes:
      - vol-postgres2:/var/lib/postgresql-ftu/data/pgdata:rw
      - ./opt/sql/create-db:/docker-entrypoint-initdb.d:rw

  kafka_manager:
    image: hlebalbau/kafka-manager:stable
    networks:
      nw_prognimak: null
    ports:
      - 9090:9000
    environment:
      ZK_HOSTS: "zookeeper-01:2181,zookeeper-02:2181,zookeeper-01:2181"
      APPLICATION_SECRET: "random-secret"

  kafka-trade:
    image: prognimak.app/kafka-trade:01
    networks:
      nw_prognimak: null
    ports:
      - 9080:8080
    environment:
      DDL_AUTO: create
      KAFKA_BOOTSTRAP_ADDRESS: 'kafka-01:9092'
      APP_KAFKA_REPLICATION_FACTOR: 2
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres:5432/test_db'
    depends_on:
      - postgres

#  kafka_ui:
#    image: provectuslabs/kafka-ui:latest
#    networks:
#      nw_prognimak: null
#    ports:
#      - 9090:9000
#    environment:
#      KAFKA_CLUSTERS_0_NAME: 'local'
#      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'kafka-01:9092,kafka-02:9092'

networks:
  nw_prognimak:
    driver: bridge

volumes:
    vol-postgres2: {}
    vol-kafka-1: {}
    vol-zk-1: {}
    vol-kafka-2: {}
    vol-zk-2: {}
    vol-zk-3: {}
